refactor(landing): prod 18
exegov-ai/exegov-landing pull request #20
Opened 2024-08-06 12:27 UTC by johnnieskywalker

2024-08-06 12:49 UTC, johnnieskywalker commented
![image](https://github.com/user-attachments/assets/cac11863-1e99-4f85-b72c-20ba64628f4a)

2024-08-06 13:43 UTC, johnnieskywalker commented
![image](https://github.com/user-attachments/assets/620bd819-57bf-439d-84c2-1d5730e145e5)

2024-08-07 11:24 UTC, Denyllon requested changes

2024-08-07 11:24 UTC, Denyllon commented on src/components/list-section/index.tsx
> +    We offer coaching and training to build effective teams, foster innovation, and drive strategic goals.
Typo: faster*

Recommendaton: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2024-08-07 11:24 UTC, Denyllon commented on src/components/list-section/index.tsx
> +    description: `FScale your business with confidence and precision.
Typo: Scale*

2024-08-07 11:24 UTC, Denyllon commented on src/components/why-section/index.tsx
> +            <p className={tw(`mt-2 text-5xl lg:text-7xl font-bold tracking-tight text-gray-900`)}>Why Chose Exegov?</p>
Typo: Choose*

2024-08-07 12:35 UTC, Denyllon commented
Besides the above things:
1. It seems the "Get in touch" section does not have padding over 768px
2. We could consider making the company icons smaller than right now
3. The "Why choose Exegov" section should shrink immediately into one column layout, instead of two. 

<img width="959" alt="Screenshot 2024-08-07 at 14 35 30" src="https://github.com/user-attachments/assets/e77c1013-6f19-4421-8e44-d0bf780a53cd">
<img width="848" alt="Screenshot 2024-08-07 at 14 31 58" src="https://github.com/user-attachments/assets/b912cce2-fdbb-440c-933b-923d0cf133b8">

2024-08-07 16:33 UTC, johnnieskywalker commented on src/components/list-section/index.tsx
> +    We offer coaching and training to build effective teams, foster innovation, and drive strategic goals.
I think @bartexegov meant foster

2024-08-09 11:35 UTC, merged